class Config {
  static APP_NAME = "Sablier";

  static DUMMY_CONTENT = {};

  static DEFAULT_DECIMAL_SEPARATOR = ".";

  static DEFAULT_DECIMAL_LOCALE = "en";

  /**
   * ROUTERS
   */

  static ROUTE_PAGE_DASHBOARD = "/dashboard";

  static ROUTE_PAGE_STREAM_CLEAN = "/stream";

  static ROUTE_PAGE_STREAM = this.ROUTE_PAGE_STREAM_CLEAN + "/:ID";

  static ROUTE_PAGE_STREAM_DETAILS = this.ROUTE_PAGE_STREAM + "/details";

  static ROUTE_PAGE_STREAM_HISTORY = this.ROUTE_PAGE_STREAM + "/history";

  static ROUTE_PAGE_STREAM_OPTIONS = this.ROUTE_PAGE_STREAM + "/options";

  /**
   * REDUX ACTIONS
   */

  /**
   *
   * VIEW
   *
   */

  static REDUX_ACTION_VIEW_OVERLAY_TOGGLE = "REDUX_ACTION_VIEW_OVERLAY_TOGGLE";

  static REDUX_ACTION_VIEW_OVERLAY_OPEN = "REDUX_ACTION_VIEW_OVERLAY_OPEN";

  static REDUX_ACTION_VIEW_OVERLAY_CLOSE = "REDUX_ACTION_VIEW_OVERLAY_CLOSE";

  static REDUX_ACTION_VIEW_OVERLAY_RESET = "REDUX_ACTION_VIEW_OVERLAY_RESET";

  static REDUX_ACTION_VIEW_COVER_TOGGLE = "REDUX_ACTION_VIEW_COVER_TOGGLE";

  static REDUX_ACTION_VIEW_COVER_OPEN = "REDUX_ACTION_VIEW_COVER_OPEN";

  static REDUX_ACTION_VIEW_COVER_CLOSE = "REDUX_ACTION_VIEW_COVER_CLOSE";

  static REDUX_ACTION_VIEW_COVER_RESET = "REDUX_ACTION_VIEW_COVER_RESET";

  static REDUX_ACTION_VIEW_COMMON_DOCUMENT_BACKGROUND_SCROLL_ENABLE =
    "REDUX_ACTION_VIEW_COMMON_DOCUMENT_BACKGROUND_SCROLL_ENABLE";

  static REDUX_ACTION_VIEW_COMMON_DOCUMENT_BACKGROUND_SCROLL_DISABLE =
    "REDUX_ACTION_VIEW_COMMON_DOCUMENT_BACKGROUND_SCROLL_DISABLE";

  /**
   *
   * MODEL
   *
   */

  static REDUX_ACTION_MODEL_COVER_STREAM_CHOOSE = "REDUX_ACTION_MODEL_COVER_STREAM_CHOOSE";

  static REDUX_ACTION_MODEL_STREAM_SET_ACTIVE = "REDUX_ACTION_MODEL_STREAM_SET_ACTIVE";

  /**
   *
   * CONTROLLER
   *
   */

  static REDUX_ACTION_CONTROLLER_COVER_STREAM_CHOOSE = "REDUX_ACTION_CONTROLLER_COVER_STREAM_CHOOSE";

  static REDUX_ACTION_CONTROLLER_COVER_CLOSE = "REDUX_ACTION_CONTROLLER_COVER_CLOSE";

  /**
   * PROJECT VARIABLES
   */

  static STREAM_CONTEXT_CARD_HIDDEN = null;

  static STREAM_CONTEXT_CARD_DETAILS = "details";

  static STREAM_CONTEXT_CARD_HISTORY = "history";

  static STREAM_HISTORY_TYPE_WITHDRAW_MANUAL = "withdraw_manual";

  static STREAM_HISTORY_TYPE_WITHDRAW_AUTO = "withdraw_auto";

  static STREAM_HISTORY_TYPE_DEPOSIT = "deposit";
}

export default Config;
